# -*- coding: utf-8 -*-
"""ETL_com_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UTztpe3L2INQvP2ztz5E20jhUiKfVW4y

**ELT com Python**
"""

import pandas as pd

"""**Extract** - extração"""

df= pd.read_csv("https://pycourse.s3.amazonaws.com/temperature.csv")
df

"""**Transform** - transformação"""

df['classification'].value_counts()

"""**Load** - carregamento"""

df['classification'].value_counts().plot(style='-o', linewidth=2.5, color='#b05dcf', figsize=(10, 5), grid=True);